version: '3'

name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=6001
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}/qbittorrent/config:/config
      - ${STORAGE_PATH}/downloads/torrents:/downloads
    ports:
      - '6001:6001'
      - '62609:62609'

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}/jackett/downloads:/downloads
      - ${CONFIG_PATH}/jackett/config:/config
    ports:
      - '9117:9117'

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${STORAGE_PATH}/videos/radarr:/movies
      - ${STORAGE_PATH}/videos/sonarr:/tv
      - ${CONFIG_PATH}/bazarr/appdata/config:/config
    ports:
      - '6767:6767'

  overseerr:
    image: sctx/overseerr
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PORT=5055
    volumes:
      - ${CONFIG_PATH}/overseerr/config:/app/config
    ports:
      - '5055:5055'

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    depends_on:
      - flaresolverr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}/prowlarr/config:/config
    ports:
      - '9696:9696'

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/flaresolverr/config:/config
    ports:
      - '8191:8191'

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${STORAGE_PATH}/downloads/nzbget:/downloads
      - ${STORAGE_PATH}/downloads/nzbget/incomplete:/incomplete-downloads
      - ${CONFIG_PATH}/nzbget/config:/config
    ports:
      - '6789:6789'

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}/radarr/appdata/config:/config
      - ${STORAGE_PATH}/downloads/torrents:/downloads
      - ${STORAGE_PATH}/videos/radarr/movies:/movies
      - ${STORAGE_PATH}/videos/radarr/anime:/anime
    ports:
      - '7878:7878'

  readarr:
    image: ghcr.io/linuxserver/readarr:0.4.19-nightly
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}/readarr/appdata/config:/config
      - ${STORAGE_PATH}/downloads/torrents:/downloads
      - ${STORAGE_PATH}/books/readarr:/books
    ports:
      - '8787:8787'

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONFIG_PATH}/sonarr/appdata/config:/config
      - ${STORAGE_PATH}/videos/sonarr:/tv
      - ${STORAGE_PATH}/downloads/torrents:/downloads
    ports:
      - '8989:8989'

  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - VA_DRIVER=IHD
      - PLEX_HW_TRANS_MAX=16
    volumes:
      - ${CONFIG_PATH}/plex/config:/config
      - ${CONFIG_PATH}/plex/data:/data
      - ${CONFIG_PATH}/plex/transcode:/transcode
      - ${STORAGE_PATH}/videos:/media
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
