networks:
  pihole_network:
    driver: bridge

services:
  cloudflared:
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    environment:
      UPSTREAM1: https://1.1.1.1/dns-query
      UPSTREAM2: https://1.0.0.1/dns-query
      PORT: 5054
      ADDRESS: 0.0.0.0
    networks:
      - pihole_network

  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on:
      - cloudflared
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: America/Sao_Paulo
      FTLCONF_webserver_api_password: ekCiN8!8b8ciNt2YmFAER
      FTLCONF_dns_upstreams: cloudflared#5054
    volumes:
      - ${CONFIG_PATH}/pihole:/etc/pihole
      - ${CONFIG_PATH}/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - SYS_NICE
    networks:
      - pihole_network
