services:
  wger-web:
    image: wger/server:latest
    depends_on:
      wger-db:
        condition: service_healthy
      wger-cache:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ${STORAGE_PATH}/wger/static:/home/wger/static
      - ${STORAGE_PATH}/wger/media:/home/wger/media
    expose:
      - 8084
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8084
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  wger-nginx:
    image: nginx:stable
    depends_on:
      - wger-web
    volumes:
      - ${CONFIG_PATH}/wger/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${STORAGE_PATH}/wger/static:/wger/static:ro
      - ${STORAGE_PATH}/wger/media:/wger/media:ro
    ports:
      - "8083:80"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  wger-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
      - TZ=Europe/Berlin
    volumes:
      - wger-postgres-data:/var/lib/postgresql/data/
    expose:
      - 5433
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  wger-cache:
    image: redis
    expose:
      - 6380
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - wger-redis-data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    mem_limit: 1gb

  wger-celery_worker:
    image: wger/server:latest
    command: /start-worker
    env_file:
      - .env
    volumes:
      - ${STORAGE_PATH}/wger/media:/home/wger/media
    depends_on:
      wger-web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wger-celery_beat:
    image: wger/server:latest
    command: /start-beat
    volumes:
      - wger-celery-beat:/home/wger/beat/
    env_file:
      - .env
    depends_on:
      wger-celery_worker:
        condition: service_healthy

volumes:
  wger-postgres-data:
  wger-celery-beat:
  wger-redis-data:

networks:
  default:
    name: wger_network
